import MainHero from "@/components/UI/Home/MainHero";
import HomeDeals from "@/components/UI/Home/homeDeals/HomeDeals";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="mb-auto">
      <MainHero />
      <HomeDeals />
    </div>
  );
}
